language: generic

env:
 - CABALVER=2.2 GHCVER=8.2.2
 - CABALVER=2.2 GHCVER=8.4.2
 - CABALVER=2.2 GHCVER=8.6.3
 - CABALVER=head GHCVER=head  # see section about GHC HEAD snapshots
 - STACK=yaml
 - STACK=nightly

matrix:
  allow_failures:
   - env: CABALVER=head GHCVER=head
   - env: STACK=nightly

# Note: the distinction between `before_install` and `install` is not important.
before_install:
 - mkdir -p ~/.local/bin
 - export PATH=~/.local/bin:$PATH

 # Cabal
 - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH
 - test -z "$CABALVER" || bash ./.travis-setup-linux.sh


 # Stack
 # install stack
 - test -z "$STACK" || { travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack' ; }
 # stack solver needs cabal :-(
 - test -z "$STACK" || test "$STACK" = "yaml"  || sudo add-apt-repository -y ppa:hvr/ghc
 - test -z "$STACK" || test "$STACK" = "yaml"  || travis_retry sudo apt-get update
 - test -z "$STACK" || test "$STACK" = "yaml"  || travis_retry sudo apt-get install cabal-install-1.24
 - test -z "$STACK" || test "$STACK" = "yaml"  || export PATH=/opt/cabal/1.24/bin:$PATH

 - test -z "$STACK" || travis_retry sudo apt-get install g++ gcc libc6-dev libffi-dev libgmp-dev make xz-utils zlib1g-dev libwww-perl libx11-dev libxrandr-dev libxinerama-dev

 - 'test -z "$STACK" || test "$STACK" = "yaml"  || RESOLVER="$(HEAD -S https://www.stackage.org/$STACK|grep HEAD|tail -n1|cut -d/ -f4)"'
 - test -z "$STACK" || test "$STACK" = "yaml" || stack setup --resolver $RESOLVER

install:
 - 'test -z "$STACK" || test "$STACK" = "yaml" || echo "resolver: $RESOLVER" > stack.yaml'
 - test -z "$STACK" || test "$STACK" = "yaml" || stack solver --update-config
 - test -z "$STACK" || stack build --only-dependencies

script:
 - test -z "$CABALVER" || cabal new-configure --enable-tests --enable-benchmarks -v2
 - test -z "$CABALVER" || cabal new-build
 - test -z "$CABALVER" || cabal new-test
 - test -z "$CABALVER" || cabal check
 - test -z "$CABALVER" || cabal sdist
 - test -z "$STACK" || stack build --test


# The following scriptlet checks that the resulting source distribution can be built & installed
 - test -z "$CABALVER" || {
   export SRC_TGZ=$(cabal info . | awk '{print $2 ".tar.gz";exit}') ;
   cd dist/;
   if [ -f "$SRC_TGZ" ]; then
      cabal install --force-reinstalls "$SRC_TGZ";
   else
      echo "expected '$SRC_TGZ' not found";
      exit 1;
   fi;
   }


jobs:
  include:
    - stage: deploy
      env: DOCS=yes
      before_install: travis_retry sudo apt-get install xsltproc docbook-xsl
      script:
       - make -C doc html
       - mkdir -p website/doc
       - mv doc/users_guide website/doc
      deploy:
         provider: pages
         skip_cleanup: true
         github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
         fqdn: arbtt.nomeata.de
         local_dir: website
         on:
           branch: master
